# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hanish Paturi
description: >- # this means to ignore newlines until "baseurl:"
  Data Scientist and Analyst project portfolio for Hanish Paturi.
  This site is built with Jekyll and hosted on GitHub Pages.
  The theme used is Minimal Mistakes by Michael Rose.
  See https://mmistakes.github.io/minimal-mistakes/ for details.
email: hanishpaturi1320@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hantablack9.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: your_twitter_handle
github_username:  hantablack9

# Build settings
# theme: minima # this is the default theme
remote_theme: "mmistakes/minimal-mistakes" # This is the line that adds the Minimal Mistakes theme
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file paths under the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
